spring.application.name=currency-convertor
server.port=8080
spring.jackson.serialization.indent-output=true
frontend.url=${FRONTEND_URL}
spring.web.cors.allowed-origin-patterns=${frontend.url}
exchange.api.url=${EXCHANGE_API_URL}
exchange.api.key=${EXCHANGE_API_KEY}